services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: csat-timescaledb
    ports:
      - "5654:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cast2025!@
      POSTGRES_DB: cast_development
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

volumes:
  timescaledb_data: