#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "백엔드 테스트 시작"
if git diff --name-only HEAD~1 | grep -q "^backend/"; then
  cd backend
  npm test
  cd ..
  if [ $? -ne 0 ]; then
    echo "백엔드 테스트 실패"
    exit 1
  fi
  echo "백엔드 테스트 통과"
else
  echo "백엔드 변경사항 없음(테스트 건너뛰기)"
fi
