#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only @{upstream}..HEAD | grep -q "^backend/"; then
  cd backend
    # npm test || { echo "백엔드 테스트 실패"; exit 1; }
  echo "백엔드 테스트 통과"
else
  echo "백엔드 변경사항 없음"
fi
